name: Unlock Files after Merge

on:
  push:
    branches:
      - development-donotdelete

jobs:
  unlock-after-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Authenticate with Personal Access Token
        env:
          GH_TOKEN: ${{ secrets.LFS_PAT }}
        run: |
          git config --global user.name "MinerSheep"
          git config --global user.email "ryderpbnj@gmail.com"
          git remote set-url origin https://${{ secrets.LFS_PAT }}@github.com/${{ github.repository }}

      - name: Debug Git Authentication with the PAT
        run: |
          git config --get remote.origin.url
          curl -I -H "Authorization: token ${{ secrets.LFS_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}

      - name: Unlock merged files
        run: |
          OWNER="MinerSheep"
          REPO="TheRespawnBureau"

          # git locks
          git lfs install
          git lfs locks

          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}")

          # For each changed file, check if it is locked
          echo "$CHANGED_FILES" | while IFS= read -r f; do
            [ -z "$f" ] && continue

            echo "Checking for lock on: $f"

            # Check locally which locks exist
            LOCAL_LOCK=$(git lfs locks | awk -v file="$f" '$1 == file {print $2}')

            if [ -z "$LOCAL_LOCK" ]; then
              echo "  -> No local lock entry for $f"
              continue
            fi

            echo "  -> Found local lock id: $LOCAL_LOCK"

            # Look up lock on GitHub API for this path
            LOCK_JSON=$(curl -s \
              -H "Authorization: token ${{ secrets.LFS_PAT }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${OWNER}/${REPO}/git/lfs/locks?path=$(jq -rn --arg p "$f" '$p|@uri')")

            LOCK_ID=$(echo "$LOCK_JSON" | jq -r --arg path "$f" '.locks[]? | select(.path == $path) | .id')

            if [ -n "$LOCK_ID" ] && [ "$LOCK_ID" != "null" ]; then
              echo "  -> Force unlocking $f (lock id $LOCK_ID)"
              curl -s -X DELETE \
                -H "Authorization: token ${{ secrets.LFS_PAT }}" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/${OWNER}/${REPO}/git/lfs/locks/$LOCK_ID?force=true"
            else
              echo "  -> Lock not found in API for $f (local id was $LOCAL_LOCK)"
            fi
          done
        env:
          GIT_LFS_SKIP_SMUDGE: 1
