name: Unlock Files after Merge

on:
  push:
    branches:
      - development-donotdelete

jobs:
  unlock-after-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Authenticate with Personal Access Token
        env:
          GH_TOKEN: ${{ secrets.LFS_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.LFS_PAT }}@github.com/${{ github.repository }}

      - name: Debug Git Authentication with the PAT
        run: |
          git config --get remote.origin.url
          curl -I -H "Authorization: token ${{ secrets.LFS_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}

      - name: Unlock merged files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for f in $CHANGED_FILES; do
            git lfs unlock --force "$f" || true
          done
