name: Unlock Files after Merge

on:
  push:
    branches:
      - development-donotdelete

jobs:
  unlock-after-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Authenticate with Personal Access Token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.LFS_PAT }}@github.com/${{ github.repository }}.git

      - name: Unlock merged files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for f in $CHANGED_FILES; do
            git lfs unlock "$f" || true
          done
