name: Unlock Files after Merge

on:
  push:
    branches:
      - development-donotdelete

jobs:
  unlock-after-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Authenticate with Personal Access Token
        run: |
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "CI Bot"
          git config --global credential.helper store
          echo "https://${{ secrets.LFS_PAT }}:@github.com/${{ github.repository }}" > ~/.git-credentials

      - name: Debug Git Authentication with the PAT
        run: |
          git config --get remote.origin.url
          curl -I -H "Authorization: token ${{ secrets.LFS_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}

      - name: Unlock merged files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          for f in $CHANGED_FILES; do
            git lfs unlock "$f" || true
          done
